### ISSUE TITLE
Installation takes a long time 

### ISSUE THREAD

**Issue by Amine-7788** [suda-huanglab/circlehunter#8]
Hi Yang,

I wanna use your tool to detect ecDNA from ATACseq Data, but the first command of installation : 
conda install -n base -c conda-forge mamba
take a long time ( i keep it running overnight and didn't finished yet), also what version of python is compatible with the tool ? 

Thank you

**Comment by yangmqglobe** [comment]
Seems like your base env have installled a lot of package, this will cause conda takes forever to solving enviroment, that's the reason why I use mamba. In this case, a new mamba installation is recommanded, both micromamba or mambaforge are good choice.

**Comment by Amine-7788** [comment]
Can you please send me the full command to install in this case.
Thank you

**Comment by yangmqglobe** [comment]
https://lmstfy.net/bing/?q=bWljcm9tYW1iYQ==

**Comment by Amine-7788** [comment]
I used : 
conda install -n base -c conda-forge micromamba 
AND
micro mamba env create -f environment.yml
Then 
micromamba activate circlehunter 

I get this : 

(base) josemourinhou@Joses-MBP circlehunter-main % micromamba shell init --shell zsh --root-prefix=~/micromamba
Modifying RC file "/Users/josemourinhou/.zshrc"
Generating config for root prefix "/Users/josemourinhou/micromamba"
Setting mamba executable to: "/Users/josemourinhou/anaconda3/bin/micromamba"
Adding (or replacing) the following in your "/Users/josemourinhou/.zshrc" file

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE='/Users/josemourinhou/anaconda3/bin/micromamba';
export MAMBA_ROOT_PREFIX='/Users/josemourinhou/micromamba';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell zsh --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias micromamba="$MAMBA_EXE"  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<


do you think that  circlehunter is already activated ?

Thank you

**Comment by yangmqglobe** [comment]
no, you should read the output carefully, it has tell you the next steps!!!

**Comment by Amine-7788** [comment]
I start the run and i get this error : 

Error: Sorted input specified, but the file /Users/josemourinhou/Desktop/circlehunter-main/workspace/hg38.blacklist.bed has the following record with a different sort order than the genomeFile /Users/josemourinhou/Desktop/circlehunter-main/workspace/samples/GSM383/GSM3832733/mapping/GSM3832733.chrom_sizes
chr1	124450730	124450960
[Tue Aug  8 17:59:02 2023]
Error in rule clean_bed:
    jobid: 12
    output: /Users/josemourinhou/Desktop/circlehunter-main/workspace/samples/GSM383/GSM3832733/mapping/GSM3832733_clean.bed
    shell:
        bedtools complement -g /Users/josemourinhou/Desktop/circlehunter-main/workspace/samples/GSM383/GSM3832733/mapping/GSM3832733.chrom_sizes -i /Users/josemourinhou/Desktop/circlehunter-main/workspace/hg38.blacklist.bed > /Users/josemourinhou/Desktop/circlehunter-main/workspace/samples/GSM383/GSM3832733/mapping/GSM3832733_clean.bed
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job clean_bed since they might be corrupted:
/Users/josemourinhou/Desktop/circlehunter-main/workspace/samples/GSM383/GSM3832733/mapping/GSM3832733_clean.bed
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-08-08T161017.804854.snakemake.log

**Comment by yangmqglobe** [comment]
1. you may need to sort your genome fasta file and blacklist in nature order, which means you chr2 is next to chr1, not chr10
2. maybe check out this commit https://github.com/yangmqglobe/circlehunter/commit/35a07eb73eec107e6850a7b20dd14d4000f75d48

**Comment by Amine-7788** [comment]
I sorted the fast file and the blacklist bed file, then I get this error : 

[E::hts_idx_push] Unsorted positions on sequence #17: 48753878 followed by 48753868
[E::sam_index] Read 'SRR8236759.27' with ref_name='chr17', ref_length=83257441, flags=163, pos=48753868 cannot be indexed
samtools index: failed to create index for "/Users/josemourinhou/Desktop/circlehunter-main/workspace/samples/GSM383/GSM3832733/mapping/GSM3832733.sorted.bam"
[Tue Aug  8 19:54:26 2023]
Error in rule index:
    jobid: 9
    output: /Users/josemourinhou/Desktop/circlehunter-main/workspace/samples/GSM383/GSM3832733/mapping/GSM3832733.sorted.bam.bai
    shell:
        samtools index /Users/josemourinhou/Desktop/circlehunter-main/workspace/samples/GSM383/GSM3832733/mapping/GSM3832733.sorted.bam
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-08-08T195317.303683.snakemake.log

**Comment by Amine-7788** [comment]
Can you take a look to this error please : 

Traceback (most recent call last):
  File "/Users/josemourinhou/Desktop/circlehunter-main/tools/annotate.py", line 54, in <module>
    main()
  File "/Users/josemourinhou/Desktop/circlehunter-main/tools/annotate.py", line 29, in main
    db = pysam.TabixFile(db_path)
  File "pysam/libctabix.pyx", line 351, in pysam.libctabix.TabixFile.__cinit__
  File "pysam/libctabix.pyx", line 383, in pysam.libctabix.TabixFile._open
OSError: index `/Users/josemourinhou/Desktop/circlehunter-main/workspace/hg38_RefSeq.bed.tbi` not found
[Wed Aug  9 19:19:47 2023]
Error in rule annotate:
    jobid: 1
    output: /Users/josemourinhou/Desktop/circlehunter-main/workspace/samples/GSM383/GSM3832733/calling/GSM3832733_ecDNA_genes.bed
    shell:
        python /Users/josemourinhou/Desktop/circlehunter-main/tools/annotate.py /Users/josemourinhou/Desktop/circlehunter-main/workspace/hg38_RefSeq.bed /Users/josemourinhou/Desktop/circlehunter-main/workspace/samples/GSM383/GSM3832733/calling/GSM3832733_ecDNA.bed /Users/josemourinhou/Desktop/circlehunter-main/workspace/samples/GSM383/GSM3832733/calling/GSM3832733_ecDNA_genes.bed
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-08-09T184903.897542.snakemake.log

**Comment by Amine-7788** [comment]
I get an output (just the number of the chromosome and the coordinate) without the name of genes in this file (GSM3832733_ecDNA_genes.bed).
Any thought about this issue ?

**Comment by Amine-7788** [comment]
Can you look to this issue please.
